# ---------- BUILD ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# copia tudo da pasta MoneyFlowAPI
COPY . .

# restaurar dependências
RUN dotnet restore MoneyFlowAPI.csproj

# publicar
RUN dotnet publish MoneyFlowAPI.csproj -c Release -o /app/publish

# ---------- RUNTIME ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "MoneyFlowAPI.dll"]
